domain_path: C:\Users\nq5949\Documents\vitis6\psoc_platform\export\psoc_platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
